// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFClientGetLeaderboardAroundCharacter.h"

UPFClientGetLeaderboardAroundCharacter::UPFClientGetLeaderboardAroundCharacter(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetLeaderboardAroundCharacterDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientGetLeaderboardAroundCharacter* UPFClientGetLeaderboardAroundCharacter::GetLeaderboardAroundCharacter(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InStatisticName, const FString& InCharacterId, const FString& InCharacterType, const int32& InMaxResultsCount)
{
	UPFClientGetLeaderboardAroundCharacter* Proxy = NewObject<UPFClientGetLeaderboardAroundCharacter>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.StatisticName = InStatisticName;
	Proxy->Request.CharacterId = InCharacterId;
	Proxy->Request.CharacterType = InCharacterType;
	Proxy->Request.MaxResultsCount = InMaxResultsCount;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientGetLeaderboardAroundCharacter::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->GetLeaderboardAroundCharacter(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPClientGetLeaderboardAroundCharacterResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientGetLeaderboardAroundCharacter::OnSuccessCallback(const PlayFab::ClientModels::FGetLeaderboardAroundCharacterResult& Result)
{
	FBPClientGetLeaderboardAroundCharacterResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFClientGetLeaderboardAroundCharacter::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPClientGetLeaderboardAroundCharacterResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
