// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFClientGetUserReadOnlyData.h"

UPFClientGetUserReadOnlyData::UPFClientGetUserReadOnlyData(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetUserReadOnlyDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientGetUserReadOnlyData* UPFClientGetUserReadOnlyData::GetUserReadOnlyData(UObject* WorldContextObject, class APlayerController* PlayerController , const TArray<FString>& InKeys, const FString& InPlayFabId, const int32& InIfChangedFromDataVersion)
{
	UPFClientGetUserReadOnlyData* Proxy = NewObject<UPFClientGetUserReadOnlyData>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.Keys = InKeys;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.IfChangedFromDataVersion = InIfChangedFromDataVersion;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientGetUserReadOnlyData::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->GetUserReadOnlyData(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPClientGetUserDataResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientGetUserReadOnlyData::OnSuccessCallback(const PlayFab::ClientModels::FGetUserDataResult& Result)
{
	FBPClientGetUserDataResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFClientGetUserReadOnlyData::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPClientGetUserDataResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
