// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFClientRestoreIOSPurchases.h"

UPFClientRestoreIOSPurchases::UPFClientRestoreIOSPurchases(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FRestoreIOSPurchasesDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientRestoreIOSPurchases* UPFClientRestoreIOSPurchases::RestoreIOSPurchases(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InReceiptData)
{
	UPFClientRestoreIOSPurchases* Proxy = NewObject<UPFClientRestoreIOSPurchases>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.ReceiptData = InReceiptData;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientRestoreIOSPurchases::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->RestoreIOSPurchases(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientRestoreIOSPurchases::OnSuccessCallback(const PlayFab::ClientModels::FRestoreIOSPurchasesResult& Result)
{
	OnSuccess.Broadcast();
}

void UPFClientRestoreIOSPurchases::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
