// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFClientRegisterForIOSPushNotification.h"

UPFClientRegisterForIOSPushNotification::UPFClientRegisterForIOSPushNotification(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FRegisterForIOSPushNotificationDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientRegisterForIOSPushNotification* UPFClientRegisterForIOSPushNotification::RegisterForIOSPushNotification(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InDeviceToken, const bool& InSendPushNotificationConfirmation, const FString& InConfirmationMessage)
{
	UPFClientRegisterForIOSPushNotification* Proxy = NewObject<UPFClientRegisterForIOSPushNotification>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.DeviceToken = InDeviceToken;
	Proxy->Request.SendPushNotificationConfirmation = InSendPushNotificationConfirmation;
	Proxy->Request.ConfirmationMessage = InConfirmationMessage;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientRegisterForIOSPushNotification::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->RegisterForIOSPushNotification(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientRegisterForIOSPushNotification::OnSuccessCallback(const PlayFab::ClientModels::FRegisterForIOSPushNotificationResult& Result)
{
	OnSuccess.Broadcast();
}

void UPFClientRegisterForIOSPushNotification::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
