// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFClientGetFriendLeaderboardAroundPlayer.h"

UPFClientGetFriendLeaderboardAroundPlayer::UPFClientGetFriendLeaderboardAroundPlayer(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetFriendLeaderboardAroundPlayerDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientGetFriendLeaderboardAroundPlayer* UPFClientGetFriendLeaderboardAroundPlayer::GetFriendLeaderboardAroundPlayer(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InStatisticName, const int32& InMaxResultsCount, const FString& InPlayFabId, const bool& InIncludeSteamFriends, const bool& InIncludeFacebookFriends)
{
	UPFClientGetFriendLeaderboardAroundPlayer* Proxy = NewObject<UPFClientGetFriendLeaderboardAroundPlayer>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.StatisticName = InStatisticName;
	Proxy->Request.MaxResultsCount = InMaxResultsCount;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.IncludeSteamFriends = InIncludeSteamFriends;
	Proxy->Request.IncludeFacebookFriends = InIncludeFacebookFriends;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientGetFriendLeaderboardAroundPlayer::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->GetFriendLeaderboardAroundPlayer(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPClientGetFriendLeaderboardAroundPlayerResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientGetFriendLeaderboardAroundPlayer::OnSuccessCallback(const PlayFab::ClientModels::FGetFriendLeaderboardAroundPlayerResult& Result)
{
	FBPClientGetFriendLeaderboardAroundPlayerResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFClientGetFriendLeaderboardAroundPlayer::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPClientGetFriendLeaderboardAroundPlayerResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
