// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFClientLinkCustomID.h"

UPFClientLinkCustomID::UPFClientLinkCustomID(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FLinkCustomIDDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientLinkCustomID* UPFClientLinkCustomID::LinkCustomID(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InCustomId)
{
	UPFClientLinkCustomID* Proxy = NewObject<UPFClientLinkCustomID>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.CustomId = InCustomId;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientLinkCustomID::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->LinkCustomID(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientLinkCustomID::OnSuccessCallback(const PlayFab::ClientModels::FLinkCustomIDResult& Result)
{
	OnSuccess.Broadcast();
}

void UPFClientLinkCustomID::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
