// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFMatchmakerPlayerJoined.h"

UPFMatchmakerPlayerJoined::UPFMatchmakerPlayerJoined(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabMatchmakerAPI::FPlayerJoinedDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFMatchmakerPlayerJoined* UPFMatchmakerPlayerJoined::PlayerJoined(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InLobbyId, const FString& InPlayFabId)
{
	UPFMatchmakerPlayerJoined* Proxy = NewObject<UPFMatchmakerPlayerJoined>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.LobbyId = InLobbyId;
	Proxy->Request.PlayFabId = InPlayFabId;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFMatchmakerPlayerJoined::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabMatchmakerPtr MatchmakerAPI = IPlayFabModuleInterface::Get().GetMatchmakerAPI();

	bool CallResult = false;

	if(MatchmakerAPI.IsValid())
	{	
		CallResult = MatchmakerAPI->PlayerJoined(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFMatchmakerPlayerJoined::OnSuccessCallback(const PlayFab::MatchmakerModels::FPlayerJoinedResponse& Result)
{
	OnSuccess.Broadcast();
}

void UPFMatchmakerPlayerJoined::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
