// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminCreateCloudScriptTask.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFAdminCreateCloudScriptTask : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPAdminCreateTaskResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPAdminCreateTaskResultDelegate OnFailure;
	
	// Create a CloudScript task, which can run a CloudScript on a schedule.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Admin|ScheduledTask")
	static UPFAdminCreateCloudScriptTask* CreateCloudScriptTask(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InName, const FString& InDescription, const FString& InSchedule, const bool& InIsActive, const FBPAdminCloudScriptTaskParameter& InParameter);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::AdminModels::FCreateCloudScriptTaskRequest Request;

	PlayFab::UPlayFabAdminAPI::FCreateCloudScriptTaskDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::AdminModels::FCreateTaskResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
