// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminRemoveServerBuild.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFAdminRemoveServerBuild : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnSuccess; 

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnFailure; 
	
	// Removes the game server executable specified from the set of those a client is permitted to request in a call to StartGame
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Admin|Custom Server Management")
	static UPFAdminRemoveServerBuild* RemoveServerBuild(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InBuildId);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::AdminModels::FRemoveServerBuildRequest Request;

	PlayFab::UPlayFabAdminAPI::FRemoveServerBuildDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::AdminModels::FRemoveServerBuildResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
