// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminGetPlayerStatisticDefinitions.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFAdminGetPlayerStatisticDefinitions : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPAdminGetPlayerStatisticDefinitionsResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPAdminGetPlayerStatisticDefinitionsResultDelegate OnFailure;
	
	// Retrieves the configuration information for all player statistics defined in the title, regardless of whether they have a reset interval.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Admin|Player Data Management")
	static UPFAdminGetPlayerStatisticDefinitions* GetPlayerStatisticDefinitions(UObject* WorldContextObject, class APlayerController* PlayerController);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	

	PlayFab::UPlayFabAdminAPI::FGetPlayerStatisticDefinitionsDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::AdminModels::FGetPlayerStatisticDefinitionsResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
