// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminRunTask.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFAdminRunTask : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPAdminRunTaskResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPAdminRunTaskResultDelegate OnFailure;
	
	// Run a task immediately regardless of its schedule.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Admin|ScheduledTask")
	static UPFAdminRunTask* RunTask(UObject* WorldContextObject, class APlayerController* PlayerController, const FBPAdminNameIdentifier& InIdentifier);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::AdminModels::FRunTaskRequest Request;

	PlayFab::UPlayFabAdminAPI::FRunTaskDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::AdminModels::FRunTaskResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
