// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminGetPlayerTags.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFAdminGetPlayerTags : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPAdminGetPlayerTagsResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPAdminGetPlayerTagsResultDelegate OnFailure;
	
	// Get all tags with a given Namespace (optional) from a player profile.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Admin|PlayStream")
	static UPFAdminGetPlayerTags* GetPlayerTags(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InPlayFabId, const FString& InNamespace);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::AdminModels::FGetPlayerTagsRequest Request;

	PlayFab::UPlayFabAdminAPI::FGetPlayerTagsDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::AdminModels::FGetPlayerTagsResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
