// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminRevokeBans.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFAdminRevokeBans : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPAdminRevokeBansResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPAdminRevokeBansResultDelegate OnFailure;
	
	// Revoke all active bans specified with BanId.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Admin|Account Management")
	static UPFAdminRevokeBans* RevokeBans(UObject* WorldContextObject, class APlayerController* PlayerController, const TArray<FString>& InBanIds);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::AdminModels::FRevokeBansRequest Request;

	PlayFab::UPlayFabAdminAPI::FRevokeBansDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::AdminModels::FRevokeBansResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
