// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminAddPlayerTag.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFAdminAddPlayerTag : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnSuccess; 

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnFailure; 
	
	// Adds a given tag to a player profile. The tag's namespace is automatically generated based on the source of the tag.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Admin|PlayStream")
	static UPFAdminAddPlayerTag* AddPlayerTag(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InPlayFabId, const FString& InTagName);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::AdminModels::FAddPlayerTagRequest Request;

	PlayFab::UPlayFabAdminAPI::FAddPlayerTagDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::AdminModels::FAddPlayerTagResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
