// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientUpdateUserStatistics.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientUpdateUserStatistics : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnSuccess; 

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnFailure; 
	
	// Updates the values of the specified title-specific statistics for the user
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Player Data Management")
	static UPFClientUpdateUserStatistics* UpdateUserStatistics(UObject* WorldContextObject, class APlayerController* PlayerController, const int32& InUserStatistics);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FUpdateUserStatisticsRequest Request;

	PlayFab::UPlayFabClientAPI::FUpdateUserStatisticsDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FUpdateUserStatisticsResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
