// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetGameServerRegions.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientGetGameServerRegions : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPClientGameServerRegionsResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPClientGameServerRegionsResultDelegate OnFailure;
	
	//  Get details about the regions hosting game servers matching the given parameters.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Matchmaking APIs")
	static UPFClientGetGameServerRegions* GetGameServerRegions(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InBuildVersion, const FString& InTitleId);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FGameServerRegionsRequest Request;

	PlayFab::UPlayFabClientAPI::FGetGameServerRegionsDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FGameServerRegionsResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
