// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetFriendsList.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientGetFriendsList : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPClientGetFriendsListResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPClientGetFriendsListResultDelegate OnFailure;
	
	// Retrieves the current friend list for the local user, constrained to users who have PlayFab accounts. Friends from linked accounts (Facebook, Steam) are also included. You may optionally exclude some linked services' friends.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Friend List Management")
	static UPFClientGetFriendsList* GetFriendsList(UObject* WorldContextObject, class APlayerController* PlayerController, const bool& InIncludeSteamFriends, const bool& InIncludeFacebookFriends);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FGetFriendsListRequest Request;

	PlayFab::UPlayFabClientAPI::FGetFriendsListDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FGetFriendsListResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
