// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetPlayerTrades.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientGetPlayerTrades : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPClientGetPlayerTradesResponseDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPClientGetPlayerTradesResponseDelegate OnFailure;
	
	// Gets all trades the player has either opened or accepted, optionally filtered by trade status.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Trading")
	static UPFClientGetPlayerTrades* GetPlayerTrades(UObject* WorldContextObject, class APlayerController* PlayerController);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FGetPlayerTradesRequest Request;

	PlayFab::UPlayFabClientAPI::FGetPlayerTradesDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FGetPlayerTradesResponse& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
