// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientConsumePSNEntitlements.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientConsumePSNEntitlements : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPClientConsumePSNEntitlementsResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPClientConsumePSNEntitlementsResultDelegate OnFailure;
	
	// Checks for any new consumable entitlements. If any are found, they are consumed and added as PlayFab items
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Sony-specific APIs")
	static UPFClientConsumePSNEntitlements* ConsumePSNEntitlements(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InCatalogVersion, const int32& InServiceLabel);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FConsumePSNEntitlementsRequest Request;

	PlayFab::UPlayFabClientAPI::FConsumePSNEntitlementsDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FConsumePSNEntitlementsResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
