// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetStoreItems.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientGetStoreItems : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPClientGetStoreItemsResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPClientGetStoreItemsResultDelegate OnFailure;
	
	// Retrieves the set of items defined for the specified store, including all prices defined
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Title-Wide Data Management")
	static UPFClientGetStoreItems* GetStoreItems(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InStoreId, const FString& InCatalogVersion);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FGetStoreItemsRequest Request;

	PlayFab::UPlayFabClientAPI::FGetStoreItemsDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FGetStoreItemsResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
