// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientUpdateUserTitleDisplayName.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientUpdateUserTitleDisplayName : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPClientUpdateUserTitleDisplayNameResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPClientUpdateUserTitleDisplayNameResultDelegate OnFailure;
	
	// Updates the title specific display name for the user
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Account Management")
	static UPFClientUpdateUserTitleDisplayName* UpdateUserTitleDisplayName(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InDisplayName);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FUpdateUserTitleDisplayNameRequest Request;

	PlayFab::UPlayFabClientAPI::FUpdateUserTitleDisplayNameDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FUpdateUserTitleDisplayNameResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
