// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFServerLogEvent.h"

UPFServerLogEvent::UPFServerLogEvent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FLogEventDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerLogEvent* UPFServerLogEvent::LogEvent(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const FString& InEntityId, const FString& InEntityType, const FDateTime& InTimestamp, const FString& InEventName, const bool& InProfileSetEvent)
{
	UPFServerLogEvent* Proxy = NewObject<UPFServerLogEvent>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.EntityId = InEntityId;
	Proxy->Request.EntityType = InEntityType;
	
	Proxy->Request.EventName = InEventName;
	
	Proxy->Request.ProfileSetEvent = InProfileSetEvent;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerLogEvent::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->LogEvent(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerLogEvent::OnSuccessCallback(const PlayFab::ServerModels::FLogEventResult& Result)
{
	OnSuccess.Broadcast();
}

void UPFServerLogEvent::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
