// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFServerNotifyMatchmakerPlayerLeft.h"

UPFServerNotifyMatchmakerPlayerLeft::UPFServerNotifyMatchmakerPlayerLeft(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FNotifyMatchmakerPlayerLeftDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerNotifyMatchmakerPlayerLeft* UPFServerNotifyMatchmakerPlayerLeft::NotifyMatchmakerPlayerLeft(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InLobbyId, const FString& InPlayFabId)
{
	UPFServerNotifyMatchmakerPlayerLeft* Proxy = NewObject<UPFServerNotifyMatchmakerPlayerLeft>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.LobbyId = InLobbyId;
	Proxy->Request.PlayFabId = InPlayFabId;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerNotifyMatchmakerPlayerLeft::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->NotifyMatchmakerPlayerLeft(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPServerNotifyMatchmakerPlayerLeftResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerNotifyMatchmakerPlayerLeft::OnSuccessCallback(const PlayFab::ServerModels::FNotifyMatchmakerPlayerLeftResult& Result)
{
	FBPServerNotifyMatchmakerPlayerLeftResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFServerNotifyMatchmakerPlayerLeft::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPServerNotifyMatchmakerPlayerLeftResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
