// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFServerGetCloudScriptUrl.h"

UPFServerGetCloudScriptUrl::UPFServerGetCloudScriptUrl(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FGetCloudScriptUrlDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerGetCloudScriptUrl* UPFServerGetCloudScriptUrl::GetCloudScriptUrl(UObject* WorldContextObject, class APlayerController* PlayerController , const int32& InVersion, const bool& InTesting)
{
	UPFServerGetCloudScriptUrl* Proxy = NewObject<UPFServerGetCloudScriptUrl>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.Version = InVersion;
	Proxy->Request.Testing = InTesting;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerGetCloudScriptUrl::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->GetCloudScriptUrl(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPServerGetCloudScriptUrlResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerGetCloudScriptUrl::OnSuccessCallback(const PlayFab::ServerModels::FGetCloudScriptUrlResult& Result)
{
	FBPServerGetCloudScriptUrlResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFServerGetCloudScriptUrl::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPServerGetCloudScriptUrlResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
