// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFServerGetCharacterReadOnlyData.h"

UPFServerGetCharacterReadOnlyData::UPFServerGetCharacterReadOnlyData(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FGetCharacterReadOnlyDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerGetCharacterReadOnlyData* UPFServerGetCharacterReadOnlyData::GetCharacterReadOnlyData(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const FString& InCharacterId, const TArray<FString>& InKeys, const int32& InIfChangedFromDataVersion)
{
	UPFServerGetCharacterReadOnlyData* Proxy = NewObject<UPFServerGetCharacterReadOnlyData>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.CharacterId = InCharacterId;
	Proxy->Request.Keys = InKeys;
	Proxy->Request.IfChangedFromDataVersion = InIfChangedFromDataVersion;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerGetCharacterReadOnlyData::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->GetCharacterReadOnlyData(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPServerGetCharacterDataResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerGetCharacterReadOnlyData::OnSuccessCallback(const PlayFab::ServerModels::FGetCharacterDataResult& Result)
{
	FBPServerGetCharacterDataResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFServerGetCharacterReadOnlyData::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPServerGetCharacterDataResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
