// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFServerModifyItemUses.h"

UPFServerModifyItemUses::UPFServerModifyItemUses(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FModifyItemUsesDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerModifyItemUses* UPFServerModifyItemUses::ModifyItemUses(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const FString& InItemInstanceId, const int32& InUsesToAdd)
{
	UPFServerModifyItemUses* Proxy = NewObject<UPFServerModifyItemUses>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.ItemInstanceId = InItemInstanceId;
	Proxy->Request.UsesToAdd = InUsesToAdd;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerModifyItemUses::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->ModifyItemUses(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPServerModifyItemUsesResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerModifyItemUses::OnSuccessCallback(const PlayFab::ServerModels::FModifyItemUsesResult& Result)
{
	FBPServerModifyItemUsesResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFServerModifyItemUses::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPServerModifyItemUsesResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
