// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFServerExecuteCloudScript.h"

UPFServerExecuteCloudScript::UPFServerExecuteCloudScript(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FExecuteCloudScriptDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerExecuteCloudScript* UPFServerExecuteCloudScript::ExecuteCloudScript(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const FString& InFunctionName, const int32& InSpecificRevision, const bool& InGeneratePlayStreamEvent)
{
	UPFServerExecuteCloudScript* Proxy = NewObject<UPFServerExecuteCloudScript>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.FunctionName = InFunctionName;
	
	
	Proxy->Request.SpecificRevision = InSpecificRevision;
	Proxy->Request.GeneratePlayStreamEvent = InGeneratePlayStreamEvent;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerExecuteCloudScript::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->ExecuteCloudScript(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPServerExecuteCloudScriptResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerExecuteCloudScript::OnSuccessCallback(const PlayFab::ServerModels::FExecuteCloudScriptResult& Result)
{
	FBPServerExecuteCloudScriptResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFServerExecuteCloudScript::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPServerExecuteCloudScriptResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
