// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFServerDeleteCharacterFromUser.h"

UPFServerDeleteCharacterFromUser::UPFServerDeleteCharacterFromUser(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FDeleteCharacterFromUserDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerDeleteCharacterFromUser* UPFServerDeleteCharacterFromUser::DeleteCharacterFromUser(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const FString& InCharacterId, const bool& InSaveCharacterInventory)
{
	UPFServerDeleteCharacterFromUser* Proxy = NewObject<UPFServerDeleteCharacterFromUser>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.CharacterId = InCharacterId;
	Proxy->Request.SaveCharacterInventory = InSaveCharacterInventory;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerDeleteCharacterFromUser::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->DeleteCharacterFromUser(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerDeleteCharacterFromUser::OnSuccessCallback(const PlayFab::ServerModels::FDeleteCharacterFromUserResult& Result)
{
	OnSuccess.Broadcast();
}

void UPFServerDeleteCharacterFromUser::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
