// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFServerMoveItemToCharacterFromUser.h"

UPFServerMoveItemToCharacterFromUser::UPFServerMoveItemToCharacterFromUser(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FMoveItemToCharacterFromUserDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerMoveItemToCharacterFromUser* UPFServerMoveItemToCharacterFromUser::MoveItemToCharacterFromUser(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const FString& InCharacterId, const FString& InItemInstanceId)
{
	UPFServerMoveItemToCharacterFromUser* Proxy = NewObject<UPFServerMoveItemToCharacterFromUser>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.CharacterId = InCharacterId;
	Proxy->Request.ItemInstanceId = InItemInstanceId;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerMoveItemToCharacterFromUser::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->MoveItemToCharacterFromUser(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerMoveItemToCharacterFromUser::OnSuccessCallback(const PlayFab::ServerModels::FMoveItemToCharacterFromUserResult& Result)
{
	OnSuccess.Broadcast();
}

void UPFServerMoveItemToCharacterFromUser::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
