// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFServerUpdateUserPublisherReadOnlyData.h"

UPFServerUpdateUserPublisherReadOnlyData::UPFServerUpdateUserPublisherReadOnlyData(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FUpdateUserPublisherReadOnlyDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerUpdateUserPublisherReadOnlyData* UPFServerUpdateUserPublisherReadOnlyData::UpdateUserPublisherReadOnlyData(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const FString& InData)
{
	UPFServerUpdateUserPublisherReadOnlyData* Proxy = NewObject<UPFServerUpdateUserPublisherReadOnlyData>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	
	
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerUpdateUserPublisherReadOnlyData::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->UpdateUserPublisherReadOnlyData(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPServerUpdateUserDataResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerUpdateUserPublisherReadOnlyData::OnSuccessCallback(const PlayFab::ServerModels::FUpdateUserDataResult& Result)
{
	FBPServerUpdateUserDataResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFServerUpdateUserPublisherReadOnlyData::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPServerUpdateUserDataResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
