// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFServerSetTitleInternalData.h"

UPFServerSetTitleInternalData::UPFServerSetTitleInternalData(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FSetTitleInternalDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerSetTitleInternalData* UPFServerSetTitleInternalData::SetTitleInternalData(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InKey, const FString& InValue)
{
	UPFServerSetTitleInternalData* Proxy = NewObject<UPFServerSetTitleInternalData>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.Key = InKey;
	Proxy->Request.Value = InValue;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerSetTitleInternalData::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->SetTitleInternalData(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerSetTitleInternalData::OnSuccessCallback(const PlayFab::ServerModels::FSetTitleDataResult& Result)
{
	OnSuccess.Broadcast();
}

void UPFServerSetTitleInternalData::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
