// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFServerSetGameServerInstanceData.h"

UPFServerSetGameServerInstanceData::UPFServerSetGameServerInstanceData(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FSetGameServerInstanceDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerSetGameServerInstanceData* UPFServerSetGameServerInstanceData::SetGameServerInstanceData(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InLobbyId, const FString& InGameServerData)
{
	UPFServerSetGameServerInstanceData* Proxy = NewObject<UPFServerSetGameServerInstanceData>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.LobbyId = InLobbyId;
	Proxy->Request.GameServerData = InGameServerData;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerSetGameServerInstanceData::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->SetGameServerInstanceData(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerSetGameServerInstanceData::OnSuccessCallback(const PlayFab::ServerModels::FSetGameServerInstanceDataResult& Result)
{
	OnSuccess.Broadcast();
}

void UPFServerSetGameServerInstanceData::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
