// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFServerRemoveFriend.h"

UPFServerRemoveFriend::UPFServerRemoveFriend(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FRemoveFriendDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerRemoveFriend* UPFServerRemoveFriend::RemoveFriend(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InFriendPlayFabId, const FString& InPlayFabId)
{
	UPFServerRemoveFriend* Proxy = NewObject<UPFServerRemoveFriend>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.FriendPlayFabId = InFriendPlayFabId;
	Proxy->Request.PlayFabId = InPlayFabId;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerRemoveFriend::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->RemoveFriend(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerRemoveFriend::OnSuccessCallback(const PlayFab::ServerModels::FEmptyResult& Result)
{
	OnSuccess.Broadcast();
}

void UPFServerRemoveFriend::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
