// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFServerAddCharacterVirtualCurrency.h"

UPFServerAddCharacterVirtualCurrency::UPFServerAddCharacterVirtualCurrency(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FAddCharacterVirtualCurrencyDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerAddCharacterVirtualCurrency* UPFServerAddCharacterVirtualCurrency::AddCharacterVirtualCurrency(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const FString& InCharacterId, const FString& InVirtualCurrency, const int32& InAmount)
{
	UPFServerAddCharacterVirtualCurrency* Proxy = NewObject<UPFServerAddCharacterVirtualCurrency>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.CharacterId = InCharacterId;
	Proxy->Request.VirtualCurrency = InVirtualCurrency;
	Proxy->Request.Amount = InAmount;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerAddCharacterVirtualCurrency::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->AddCharacterVirtualCurrency(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPServerModifyCharacterVirtualCurrencyResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerAddCharacterVirtualCurrency::OnSuccessCallback(const PlayFab::ServerModels::FModifyCharacterVirtualCurrencyResult& Result)
{
	FBPServerModifyCharacterVirtualCurrencyResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFServerAddCharacterVirtualCurrency::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPServerModifyCharacterVirtualCurrencyResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
