// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabMatchmakerAPI.h"
#include "Core/PlayFabMatchmakerDataModels.h"
#include "Proxy/PlayFabMatchmakerBPDataModels.h"
#include "PFMatchmakerPlayerJoined.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFMatchmakerPlayerJoined : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnSuccess; 

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnFailure; 
	
	// Informs the PlayFab game server hosting service that the indicated user has joined the Game Server Instance specified
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Matchmaker|Matchmaking APIs")
	static UPFMatchmakerPlayerJoined* PlayerJoined(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InLobbyId, const FString& InPlayFabId);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::MatchmakerModels::FPlayerJoinedRequest Request;

	PlayFab::UPlayFabMatchmakerAPI::FPlayerJoinedDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::MatchmakerModels::FPlayerJoinedResponse& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
