// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFClientGetPlayFabIDsFromFacebookIDs.h"

UPFClientGetPlayFabIDsFromFacebookIDs::UPFClientGetPlayFabIDsFromFacebookIDs(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetPlayFabIDsFromFacebookIDsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientGetPlayFabIDsFromFacebookIDs* UPFClientGetPlayFabIDsFromFacebookIDs::GetPlayFabIDsFromFacebookIDs(UObject* WorldContextObject, class APlayerController* PlayerController , const TArray<FString>& InFacebookIDs)
{
	UPFClientGetPlayFabIDsFromFacebookIDs* Proxy = NewObject<UPFClientGetPlayFabIDsFromFacebookIDs>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.FacebookIDs = InFacebookIDs;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientGetPlayFabIDsFromFacebookIDs::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->GetPlayFabIDsFromFacebookIDs(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPClientGetPlayFabIDsFromFacebookIDsResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientGetPlayFabIDsFromFacebookIDs::OnSuccessCallback(const PlayFab::ClientModels::FGetPlayFabIDsFromFacebookIDsResult& Result)
{
	FBPClientGetPlayFabIDsFromFacebookIDsResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFClientGetPlayFabIDsFromFacebookIDs::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPClientGetPlayFabIDsFromFacebookIDsResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
