// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFClientGetUserStatistics.h"

UPFClientGetUserStatistics::UPFClientGetUserStatistics(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetUserStatisticsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientGetUserStatistics* UPFClientGetUserStatistics::GetUserStatistics(UObject* WorldContextObject, class APlayerController* PlayerController )
{
	UPFClientGetUserStatistics* Proxy = NewObject<UPFClientGetUserStatistics>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientGetUserStatistics::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->GetUserStatistics(SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPClientGetUserStatisticsResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientGetUserStatistics::OnSuccessCallback(const PlayFab::ClientModels::FGetUserStatisticsResult& Result)
{
	FBPClientGetUserStatisticsResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFClientGetUserStatistics::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPClientGetUserStatisticsResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
