// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFClientCancelTrade.h"

UPFClientCancelTrade::UPFClientCancelTrade(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FCancelTradeDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientCancelTrade* UPFClientCancelTrade::CancelTrade(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InTradeId)
{
	UPFClientCancelTrade* Proxy = NewObject<UPFClientCancelTrade>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.TradeId = InTradeId;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientCancelTrade::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->CancelTrade(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPClientCancelTradeResponse BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientCancelTrade::OnSuccessCallback(const PlayFab::ClientModels::FCancelTradeResponse& Result)
{
	FBPClientCancelTradeResponse BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFClientCancelTrade::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPClientCancelTradeResponse BPResult;
 	OnFailure.Broadcast(BPResult);	
}
