// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFClientRunCloudScript.h"

UPFClientRunCloudScript::UPFClientRunCloudScript(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FRunCloudScriptDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientRunCloudScript* UPFClientRunCloudScript::RunCloudScript(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InActionId, const FString& InParamsEncoded)
{
	UPFClientRunCloudScript* Proxy = NewObject<UPFClientRunCloudScript>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.ActionId = InActionId;
	
	Proxy->Request.ParamsEncoded = InParamsEncoded;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientRunCloudScript::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->RunCloudScript(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPClientRunCloudScriptResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientRunCloudScript::OnSuccessCallback(const PlayFab::ClientModels::FRunCloudScriptResult& Result)
{
	FBPClientRunCloudScriptResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFClientRunCloudScript::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPClientRunCloudScriptResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
