// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFClientGetUserCombinedInfo.h"

UPFClientGetUserCombinedInfo::UPFClientGetUserCombinedInfo(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetUserCombinedInfoDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientGetUserCombinedInfo* UPFClientGetUserCombinedInfo::GetUserCombinedInfo(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const FString& InUsername, const FString& InEmail, const FString& InTitleDisplayName, const bool& InGetAccountInfo, const bool& InGetInventory, const bool& InGetVirtualCurrency, const bool& InGetUserData, const TArray<FString>& InUserDataKeys, const bool& InGetReadOnlyData, const TArray<FString>& InReadOnlyDataKeys)
{
	UPFClientGetUserCombinedInfo* Proxy = NewObject<UPFClientGetUserCombinedInfo>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.Username = InUsername;
	Proxy->Request.Email = InEmail;
	Proxy->Request.TitleDisplayName = InTitleDisplayName;
	Proxy->Request.GetAccountInfo = InGetAccountInfo;
	Proxy->Request.GetInventory = InGetInventory;
	Proxy->Request.GetVirtualCurrency = InGetVirtualCurrency;
	Proxy->Request.GetUserData = InGetUserData;
	Proxy->Request.UserDataKeys = InUserDataKeys;
	Proxy->Request.GetReadOnlyData = InGetReadOnlyData;
	Proxy->Request.ReadOnlyDataKeys = InReadOnlyDataKeys;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientGetUserCombinedInfo::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->GetUserCombinedInfo(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPClientGetUserCombinedInfoResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientGetUserCombinedInfo::OnSuccessCallback(const PlayFab::ClientModels::FGetUserCombinedInfoResult& Result)
{
	FBPClientGetUserCombinedInfoResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFClientGetUserCombinedInfo::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPClientGetUserCombinedInfoResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
