// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFClientGetLeaderboardAroundPlayer.h"

UPFClientGetLeaderboardAroundPlayer::UPFClientGetLeaderboardAroundPlayer(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetLeaderboardAroundPlayerDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientGetLeaderboardAroundPlayer* UPFClientGetLeaderboardAroundPlayer::GetLeaderboardAroundPlayer(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const FString& InStatisticName, const int32& InMaxResultsCount)
{
	UPFClientGetLeaderboardAroundPlayer* Proxy = NewObject<UPFClientGetLeaderboardAroundPlayer>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.StatisticName = InStatisticName;
	Proxy->Request.MaxResultsCount = InMaxResultsCount;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientGetLeaderboardAroundPlayer::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->GetLeaderboardAroundPlayer(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPClientGetLeaderboardAroundPlayerResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientGetLeaderboardAroundPlayer::OnSuccessCallback(const PlayFab::ClientModels::FGetLeaderboardAroundPlayerResult& Result)
{
	FBPClientGetLeaderboardAroundPlayerResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFClientGetLeaderboardAroundPlayer::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPClientGetLeaderboardAroundPlayerResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
