// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFClientGetLeaderboardAroundCurrentUser.h"

UPFClientGetLeaderboardAroundCurrentUser::UPFClientGetLeaderboardAroundCurrentUser(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetLeaderboardAroundCurrentUserDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientGetLeaderboardAroundCurrentUser* UPFClientGetLeaderboardAroundCurrentUser::GetLeaderboardAroundCurrentUser(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InStatisticName, const int32& InMaxResultsCount)
{
	UPFClientGetLeaderboardAroundCurrentUser* Proxy = NewObject<UPFClientGetLeaderboardAroundCurrentUser>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.StatisticName = InStatisticName;
	Proxy->Request.MaxResultsCount = InMaxResultsCount;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientGetLeaderboardAroundCurrentUser::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->GetLeaderboardAroundCurrentUser(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPClientGetLeaderboardAroundCurrentUserResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientGetLeaderboardAroundCurrentUser::OnSuccessCallback(const PlayFab::ClientModels::FGetLeaderboardAroundCurrentUserResult& Result)
{
	FBPClientGetLeaderboardAroundCurrentUserResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFClientGetLeaderboardAroundCurrentUser::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPClientGetLeaderboardAroundCurrentUserResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
