// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFClientAndroidDevicePushNotificationRegistration.h"

UPFClientAndroidDevicePushNotificationRegistration::UPFClientAndroidDevicePushNotificationRegistration(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FAndroidDevicePushNotificationRegistrationDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientAndroidDevicePushNotificationRegistration* UPFClientAndroidDevicePushNotificationRegistration::AndroidDevicePushNotificationRegistration(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InDeviceToken, const bool& InSendPushNotificationConfirmation, const FString& InConfirmationMessage)
{
	UPFClientAndroidDevicePushNotificationRegistration* Proxy = NewObject<UPFClientAndroidDevicePushNotificationRegistration>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.DeviceToken = InDeviceToken;
	Proxy->Request.SendPushNotificationConfirmation = InSendPushNotificationConfirmation;
	Proxy->Request.ConfirmationMessage = InConfirmationMessage;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientAndroidDevicePushNotificationRegistration::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->AndroidDevicePushNotificationRegistration(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientAndroidDevicePushNotificationRegistration::OnSuccessCallback(const PlayFab::ClientModels::FAndroidDevicePushNotificationRegistrationResult& Result)
{
	OnSuccess.Broadcast();
}

void UPFClientAndroidDevicePushNotificationRegistration::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
