// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFClientGetCharacterStatistics.h"

UPFClientGetCharacterStatistics::UPFClientGetCharacterStatistics(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetCharacterStatisticsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientGetCharacterStatistics* UPFClientGetCharacterStatistics::GetCharacterStatistics(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InCharacterId)
{
	UPFClientGetCharacterStatistics* Proxy = NewObject<UPFClientGetCharacterStatistics>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.CharacterId = InCharacterId;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientGetCharacterStatistics::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->GetCharacterStatistics(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPClientGetCharacterStatisticsResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientGetCharacterStatistics::OnSuccessCallback(const PlayFab::ClientModels::FGetCharacterStatisticsResult& Result)
{
	FBPClientGetCharacterStatisticsResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFClientGetCharacterStatistics::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPClientGetCharacterStatisticsResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
