// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFAdminUpdateRandomResultTables.h"

UPFAdminUpdateRandomResultTables::UPFAdminUpdateRandomResultTables(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabAdminAPI::FUpdateRandomResultTablesDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFAdminUpdateRandomResultTables* UPFAdminUpdateRandomResultTables::UpdateRandomResultTables(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InCatalogVersion, const TArray<FBPAdminRandomResultTable>& InTables)
{
	UPFAdminUpdateRandomResultTables* Proxy = NewObject<UPFAdminUpdateRandomResultTables>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.CatalogVersion = InCatalogVersion;
	for (const FBPAdminRandomResultTable& elem : InTables)
    {
        Proxy->Request.Tables.Add(elem.Data);
    }

	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFAdminUpdateRandomResultTables::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

	bool CallResult = false;

	if(AdminAPI.IsValid())
	{	
		CallResult = AdminAPI->UpdateRandomResultTables(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFAdminUpdateRandomResultTables::OnSuccessCallback(const PlayFab::AdminModels::FUpdateRandomResultTablesResult& Result)
{
	OnSuccess.Broadcast();
}

void UPFAdminUpdateRandomResultTables::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
