// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFAdminDeleteTask.h"

UPFAdminDeleteTask::UPFAdminDeleteTask(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabAdminAPI::FDeleteTaskDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFAdminDeleteTask* UPFAdminDeleteTask::DeleteTask(UObject* WorldContextObject, class APlayerController* PlayerController , const FBPAdminNameIdentifier& InIdentifier)
{
	UPFAdminDeleteTask* Proxy = NewObject<UPFAdminDeleteTask>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	*Proxy->Request.Identifier = InIdentifier.Data;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFAdminDeleteTask::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

	bool CallResult = false;

	if(AdminAPI.IsValid())
	{	
		CallResult = AdminAPI->DeleteTask(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFAdminDeleteTask::OnSuccessCallback(const PlayFab::AdminModels::FEmptyResult& Result)
{
	OnSuccess.Broadcast();
}

void UPFAdminDeleteTask::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
