// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFAdminGetUserPublisherData.h"

UPFAdminGetUserPublisherData::UPFAdminGetUserPublisherData(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabAdminAPI::FGetUserPublisherDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFAdminGetUserPublisherData* UPFAdminGetUserPublisherData::GetUserPublisherData(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const TArray<FString>& InKeys, const int32& InIfChangedFromDataVersion)
{
	UPFAdminGetUserPublisherData* Proxy = NewObject<UPFAdminGetUserPublisherData>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.Keys = InKeys;
	Proxy->Request.IfChangedFromDataVersion = InIfChangedFromDataVersion;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFAdminGetUserPublisherData::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

	bool CallResult = false;

	if(AdminAPI.IsValid())
	{	
		CallResult = AdminAPI->GetUserPublisherData(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPAdminGetUserDataResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFAdminGetUserPublisherData::OnSuccessCallback(const PlayFab::AdminModels::FGetUserDataResult& Result)
{
	FBPAdminGetUserDataResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFAdminGetUserPublisherData::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPAdminGetUserDataResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
