// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminGetMatchmakerGameModes.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFAdminGetMatchmakerGameModes : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPAdminGetMatchmakerGameModesResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPAdminGetMatchmakerGameModesResultDelegate OnFailure;
	
	// Retrieves the details of defined game modes for the specified game server executable
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Admin|Matchmaking APIs")
	static UPFAdminGetMatchmakerGameModes* GetMatchmakerGameModes(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InBuildVersion);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::AdminModels::FGetMatchmakerGameModesRequest Request;

	PlayFab::UPlayFabAdminAPI::FGetMatchmakerGameModesDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::AdminModels::FGetMatchmakerGameModesResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
