// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminBanUsers.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFAdminBanUsers : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPAdminBanUsersResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPAdminBanUsersResultDelegate OnFailure;
	
	// Bans users by PlayFab ID with optional IP address, or MAC address for the provided game.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Admin|Account Management")
	static UPFAdminBanUsers* BanUsers(UObject* WorldContextObject, class APlayerController* PlayerController, const TArray<FBPAdminBanRequest>& InBans);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::AdminModels::FBanUsersRequest Request;

	PlayFab::UPlayFabAdminAPI::FBanUsersDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::AdminModels::FBanUsersResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
