// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminSendAccountRecoveryEmail.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFAdminSendAccountRecoveryEmail : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnSuccess; 

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnFailure; 
	
	// Forces an email to be sent to the registered email address for the specified account, with a link allowing the user to change the password
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Admin|Account Management")
	static UPFAdminSendAccountRecoveryEmail* SendAccountRecoveryEmail(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InEmail);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::AdminModels::FSendAccountRecoveryEmailRequest Request;

	PlayFab::UPlayFabAdminAPI::FSendAccountRecoveryEmailDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::AdminModels::FSendAccountRecoveryEmailResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
