// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminModifyServerBuild.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFAdminModifyServerBuild : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPAdminModifyServerBuildResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPAdminModifyServerBuildResultDelegate OnFailure;
	
	// Updates the build details for the specified game server executable
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Admin|Custom Server Management")
	static UPFAdminModifyServerBuild* ModifyServerBuild(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InBuildId, const FDateTime& InTimestamp, const int32& InMaxGamesPerHost, const FString& InCommandLineTemplate, const FString& InExecutablePath, const FString& InComment);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::AdminModels::FModifyServerBuildRequest Request;

	PlayFab::UPlayFabAdminAPI::FModifyServerBuildDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::AdminModels::FModifyServerBuildResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
