// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetPlayersInSegment.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFServerGetPlayersInSegment : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPServerGetPlayersInSegmentResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPServerGetPlayersInSegmentResultDelegate OnFailure;
	
	// Allows for paging through all players in a given segment. This API creates a snapshot of all player profiles that match the segment definition at the time of its creation and lives through the Total Seconds to Live, refreshing its life span on each subsequent use of the Continuation Token. Profiles that change during the course of paging will not be reflected in the results. AB Test segments are currently not supported by this operation.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Server|PlayStream")
	static UPFServerGetPlayersInSegment* GetPlayersInSegment(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InSegmentId, const int32& InSecondsToLive, const int32& InMaxBatchSize, const FString& InContinuationToken);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ServerModels::FGetPlayersInSegmentRequest Request;

	PlayFab::UPlayFabServerAPI::FGetPlayersInSegmentDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ServerModels::FGetPlayersInSegmentResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
