// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetLeaderboardForUserCharacters.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFServerGetLeaderboardForUserCharacters : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPServerGetLeaderboardForUsersCharactersResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPServerGetLeaderboardForUsersCharactersResultDelegate OnFailure;
	
	// Retrieves a list of all of the user's characters for the given statistic.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Server|Characters")
	static UPFServerGetLeaderboardForUserCharacters* GetLeaderboardForUserCharacters(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InStatisticName, const FString& InPlayFabId, const int32& InMaxResultsCount);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ServerModels::FGetLeaderboardForUsersCharactersRequest Request;

	PlayFab::UPlayFabServerAPI::FGetLeaderboardForUserCharactersDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ServerModels::FGetLeaderboardForUsersCharactersResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
