// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerSetGameServerInstanceState.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFServerSetGameServerInstanceState : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnSuccess; 

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnFailure; 
	
	// Sets the state of the indicated Game Server Instance
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Server|Matchmaking APIs")
	static UPFServerSetGameServerInstanceState* SetGameServerInstanceState(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InLobbyId);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ServerModels::FSetGameServerInstanceStateRequest Request;

	PlayFab::UPlayFabServerAPI::FSetGameServerInstanceStateDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ServerModels::FSetGameServerInstanceStateResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
