// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetCatalogItems.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFServerGetCatalogItems : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPServerGetCatalogItemsResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPServerGetCatalogItemsResultDelegate OnFailure;
	
	// Retrieves the specified version of the title's catalog of virtual goods, including all defined properties
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Server|Title-Wide Data Management")
	static UPFServerGetCatalogItems* GetCatalogItems(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InCatalogVersion);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ServerModels::FGetCatalogItemsRequest Request;

	PlayFab::UPlayFabServerAPI::FGetCatalogItemsDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ServerModels::FGetCatalogItemsResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
