// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetUserAccountInfo.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFServerGetUserAccountInfo : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPServerGetUserAccountInfoResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPServerGetUserAccountInfoResultDelegate OnFailure;
	
	// Retrieves the relevant details for a specified user
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Server|Account Management")
	static UPFServerGetUserAccountInfo* GetUserAccountInfo(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InPlayFabId);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ServerModels::FGetUserAccountInfoRequest Request;

	PlayFab::UPlayFabServerAPI::FGetUserAccountInfoDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ServerModels::FGetUserAccountInfoResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
