// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFAdminGetTaskInstances.h"

UPFAdminGetTaskInstances::UPFAdminGetTaskInstances(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabAdminAPI::FGetTaskInstancesDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFAdminGetTaskInstances* UPFAdminGetTaskInstances::GetTaskInstances(UObject* WorldContextObject, class APlayerController* PlayerController , const FBPAdminNameIdentifier& InTaskIdentifier, const FDateTime& InStartedAtRangeFrom, const FDateTime& InStartedAtRangeTo)
{
	UPFAdminGetTaskInstances* Proxy = NewObject<UPFAdminGetTaskInstances>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	*Proxy->Request.TaskIdentifier = InTaskIdentifier.Data;
	
	
	
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFAdminGetTaskInstances::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

	bool CallResult = false;

	if(AdminAPI.IsValid())
	{	
		CallResult = AdminAPI->GetTaskInstances(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPAdminGetTaskInstancesResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFAdminGetTaskInstances::OnSuccessCallback(const PlayFab::AdminModels::FGetTaskInstancesResult& Result)
{
	FBPAdminGetTaskInstancesResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFAdminGetTaskInstances::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPAdminGetTaskInstancesResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
