// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFAdminGetUserAccountInfo.h"

UPFAdminGetUserAccountInfo::UPFAdminGetUserAccountInfo(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabAdminAPI::FGetUserAccountInfoDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFAdminGetUserAccountInfo* UPFAdminGetUserAccountInfo::GetUserAccountInfo(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const FString& InEmail, const FString& InUsername, const FString& InTitleDisplayName)
{
	UPFAdminGetUserAccountInfo* Proxy = NewObject<UPFAdminGetUserAccountInfo>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.Email = InEmail;
	Proxy->Request.Username = InUsername;
	Proxy->Request.TitleDisplayName = InTitleDisplayName;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFAdminGetUserAccountInfo::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

	bool CallResult = false;

	if(AdminAPI.IsValid())
	{	
		CallResult = AdminAPI->GetUserAccountInfo(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPAdminLookupUserAccountInfoResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFAdminGetUserAccountInfo::OnSuccessCallback(const PlayFab::AdminModels::FLookupUserAccountInfoResult& Result)
{
	FBPAdminLookupUserAccountInfoResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFAdminGetUserAccountInfo::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPAdminLookupUserAccountInfoResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
