// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerAddUserVirtualCurrency.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFServerAddUserVirtualCurrency : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPServerModifyUserVirtualCurrencyResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPServerModifyUserVirtualCurrencyResultDelegate OnFailure;
	
	// Increments  the user's balance of the specified virtual currency by the stated amount
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Server|Player Item Management")
	static UPFServerAddUserVirtualCurrency* AddUserVirtualCurrency(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InPlayFabId, const FString& InVirtualCurrency, const int32& InAmount);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ServerModels::FAddUserVirtualCurrencyRequest Request;

	PlayFab::UPlayFabServerAPI::FAddUserVirtualCurrencyDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ServerModels::FModifyUserVirtualCurrencyResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
