// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetTitleData.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFServerGetTitleData : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPServerGetTitleDataResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPServerGetTitleDataResultDelegate OnFailure;
	
	// Retrieves the key-value store of custom title settings
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Server|Title-Wide Data Management")
	static UPFServerGetTitleData* GetTitleData(UObject* WorldContextObject, class APlayerController* PlayerController, const TArray<FString>& InKeys);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ServerModels::FGetTitleDataRequest Request;

	PlayFab::UPlayFabServerAPI::FGetTitleDataDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ServerModels::FGetTitleDataResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
