// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetLeaderboard.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFServerGetLeaderboard : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPServerGetLeaderboardResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPServerGetLeaderboardResultDelegate OnFailure;
	
	// Retrieves a list of ranked users for the given statistic, starting from the indicated point in the leaderboard
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Server|Player Data Management")
	static UPFServerGetLeaderboard* GetLeaderboard(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InStatisticName, const int32& InStartPosition, const int32& InMaxResultsCount);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ServerModels::FGetLeaderboardRequest Request;

	PlayFab::UPlayFabServerAPI::FGetLeaderboardDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ServerModels::FGetLeaderboardResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
