// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerAddPlayerTag.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFServerAddPlayerTag : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnSuccess; 

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnFailure; 
	
	// Adds a given tag to a player profile. The tag's namespace is automatically generated based on the source of the tag.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Server|PlayStream")
	static UPFServerAddPlayerTag* AddPlayerTag(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InPlayFabId, const FString& InTagName);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ServerModels::FAddPlayerTagRequest Request;

	PlayFab::UPlayFabServerAPI::FAddPlayerTagDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ServerModels::FAddPlayerTagResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
