// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetPlayerTags.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFServerGetPlayerTags : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPServerGetPlayerTagsResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPServerGetPlayerTagsResultDelegate OnFailure;
	
	// Get all tags with a given Namespace (optional) from a player profile.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Server|PlayStream")
	static UPFServerGetPlayerTags* GetPlayerTags(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InPlayFabId, const FString& InNamespace);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ServerModels::FGetPlayerTagsRequest Request;

	PlayFab::UPlayFabServerAPI::FGetPlayerTagsDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ServerModels::FGetPlayerTagsResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
