// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetPurchase.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientGetPurchase : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPClientGetPurchaseResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPClientGetPurchaseResultDelegate OnFailure;
	
	// Retrieves a completed purchase along with its current PlayFab status.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Player Item Management")
	static UPFClientGetPurchase* GetPurchase(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InOrderId);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FGetPurchaseRequest Request;

	PlayFab::UPlayFabClientAPI::FGetPurchaseDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FGetPurchaseResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
