// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetLeaderboardAroundCharacter.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientGetLeaderboardAroundCharacter : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPClientGetLeaderboardAroundCharacterResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPClientGetLeaderboardAroundCharacterResultDelegate OnFailure;
	
	// Retrieves a list of ranked characters for the given statistic, centered on the currently signed-in user
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Characters")
	static UPFClientGetLeaderboardAroundCharacter* GetLeaderboardAroundCharacter(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InStatisticName, const FString& InCharacterId, const FString& InCharacterType, const int32& InMaxResultsCount);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FGetLeaderboardAroundCharacterRequest Request;

	PlayFab::UPlayFabClientAPI::FGetLeaderboardAroundCharacterDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FGetLeaderboardAroundCharacterResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
