// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientSetFriendTags.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientSetFriendTags : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnSuccess; 

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnFailure; 
	
	// Updates the tag list for a specified user in the friend list of the local user
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Friend List Management")
	static UPFClientSetFriendTags* SetFriendTags(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InFriendPlayFabId, const TArray<FString>& InTags);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FSetFriendTagsRequest Request;

	PlayFab::UPlayFabClientAPI::FSetFriendTagsDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FSetFriendTagsResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
