// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientConsumeItem.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientConsumeItem : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPClientConsumeItemResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPClientConsumeItemResultDelegate OnFailure;
	
	// Consume uses of a consumable item. When all uses are consumed, it will be removed from the player's inventory.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Player Item Management")
	static UPFClientConsumeItem* ConsumeItem(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InItemInstanceId, const int32& InConsumeCount, const FString& InCharacterId);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FConsumeItemRequest Request;

	PlayFab::UPlayFabClientAPI::FConsumeItemDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FConsumeItemResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
