// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientRestoreIOSPurchases.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientRestoreIOSPurchases : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnSuccess; 

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnFailure; 
	
	// Restores all in-app purchases based on the given refresh receipt.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|IOS-Specific APIs")
	static UPFClientRestoreIOSPurchases* RestoreIOSPurchases(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InReceiptData);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FRestoreIOSPurchasesRequest Request;

	PlayFab::UPlayFabClientAPI::FRestoreIOSPurchasesDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FRestoreIOSPurchasesResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
