// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientRunCloudScript.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientRunCloudScript : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPClientRunCloudScriptResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPClientRunCloudScriptResultDelegate OnFailure;
	
	// Triggers a particular server action, passing the provided inputs to the hosted Cloud Script. An action in this context is a handler in the JavaScript. NOTE: Before calling this API, you must call GetCloudScriptUrl to be assigned a Cloud Script server URL. When using an official PlayFab SDK, this URL is stored internally in the SDK, but GetCloudScriptUrl must still be manually called.
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Server-Side Cloud Script")
	static UPFClientRunCloudScript* RunCloudScript(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InActionId, const FString& InParamsEncoded);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FRunCloudScriptRequest Request;

	PlayFab::UPlayFabClientAPI::FRunCloudScriptDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FRunCloudScriptResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
