// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetUserStatistics.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientGetUserStatistics : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPClientGetUserStatisticsResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPClientGetUserStatisticsResultDelegate OnFailure;
	
	// Retrieves the details of all title-specific statistics for the user
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Player Data Management")
	static UPFClientGetUserStatistics* GetUserStatistics(UObject* WorldContextObject, class APlayerController* PlayerController);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	

	PlayFab::UPlayFabClientAPI::FGetUserStatisticsDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FGetUserStatisticsResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
