// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetPlayFabIDsFromGameCenterIDs.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientGetPlayFabIDsFromGameCenterIDs : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPClientGetPlayFabIDsFromGameCenterIDsResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPClientGetPlayFabIDsFromGameCenterIDsResultDelegate OnFailure;
	
	// Retrieves the unique PlayFab identifiers for the given set of Game Center identifiers (referenced in the Game Center Programming Guide as the Player Identifier).
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Account Management")
	static UPFClientGetPlayFabIDsFromGameCenterIDs* GetPlayFabIDsFromGameCenterIDs(UObject* WorldContextObject, class APlayerController* PlayerController, const TArray<FString>& InGameCenterIDs);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FGetPlayFabIDsFromGameCenterIDsRequest Request;

	PlayFab::UPlayFabClientAPI::FGetPlayFabIDsFromGameCenterIDsDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FGetPlayFabIDsFromGameCenterIDsResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
