// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PFMatchmakerUserInfo.h"

UPFMatchmakerUserInfo::UPFMatchmakerUserInfo(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabMatchmakerAPI::FUserInfoDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFMatchmakerUserInfo* UPFMatchmakerUserInfo::UserInfo(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const int32& InMinCatalogVersion)
{
	UPFMatchmakerUserInfo* Proxy = NewObject<UPFMatchmakerUserInfo>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	Proxy->Request.MinCatalogVersion = InMinCatalogVersion;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFMatchmakerUserInfo::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabMatchmakerPtr MatchmakerAPI = IPlayFabModuleInterface::Get().GetMatchmakerAPI();

	bool CallResult = false;

	if(MatchmakerAPI.IsValid())
	{	
		CallResult = MatchmakerAPI->UserInfo(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPMatchmakerUserInfoResponse BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFMatchmakerUserInfo::OnSuccessCallback(const PlayFab::MatchmakerModels::FUserInfoResponse& Result)
{
	FBPMatchmakerUserInfoResponse BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFMatchmakerUserInfo::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPMatchmakerUserInfoResponse BPResult;
 	OnFailure.Broadcast(BPResult);	
}
